application: jsvisioneditor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(scripts/.*)
- ^(worker/.*)
- ^(gae/.*)

handlers:

- url: /static
  static_dir: appcode/static

- url: /favicon.ico
  static_files: static/files/favicon.ico
  upload: static/files/favicon.ico

- url: /robots.txt
  static_files: static/files/robots.txt
  upload: static/files/robots.txt

- url: /tasks/process
  script: process.app
  login: admin
  secure: always

- url: .*
  script: main.app
#  secure: always

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest

- name: pycrypto
  version: latest

- name: ssl
  version: "latest"
